# Generated by Django 4.0.6 on 2022-09-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='building',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='building',
            name='type_object',
            field=models.CharField(choices=[('promo', 'Промо объект'), ('living', 'Жилое'), ('non-living', 'Не жилое')], default='living', max_length=32, verbose_name='Тип объекта'),
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('flat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер квартиры')),
                ('entrance', models.IntegerField(max_length=255, verbose_name='Подъезд')),
                ('floor', models.IntegerField(max_length=255, verbose_name='Этаж')),
                ('area', models.IntegerField(max_length=255, verbose_name='Площадь')),
                ('live_area', models.IntegerField(max_length=255, null=True, verbose_name='Жилая площадь')),
                ('room_count', models.IntegerField(max_length=255, verbose_name='Кол-во комнат')),
                ('price', models.IntegerField(max_length=255, verbose_name='Цена')),
                ('type_object', models.CharField(choices=[('promo', 'Промо объект'), ('living', 'Жилое'), ('non-living', 'Не жилое')], default='living', max_length=32, verbose_name='Тип объекта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
        ),
    ]
