# Generated by Django 4.0.6 on 2022-09-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.CharField(max_length=255, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='entrance',
            field=models.IntegerField(verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='live_area',
            field=models.CharField(max_length=255, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_count',
            field=models.IntegerField(verbose_name='Кол-во комнат'),
        ),
    ]
