# Generated by Django 4.0.6 on 2022-09-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_flat_area_alter_flat_entrance_alter_flat_floor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat',
            new_name='Flat_table',
        ),
    ]
